behaviors:
  Bullet:
    trainer_type: ppo
    hyperparameters:
      batch_size: 2048
      buffer_size: 20480
      learning_rate: 0.0003
      beta: 0.005
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 4
      learning_rate_schedule: linear
      beta_schedule: constant
      epsilon_schedule: linear
    network_settings:
      normalize: false
      hidden_units: 256
      num_layers: 2
    reward_signals:
      extrinsic:
        gamma: 0.8
        strength: 1
      gail:
        gamma: 0.8
        strength: 0.1
        use_actions: true
        demo_path: Demos/BulletFinalArena.demo
    max_steps: 2000000
    time_horizon: 512
    summary_freq: 10000