behaviors:
  Bullet:
    trainer_type: ppo
    hyperparameters:
      batch_size: 4096
      buffer_size: 40960
      learning_rate: 0.0003
      beta: 0.005
      epsilon: 0.2
      lambd: 0.95
      num_epoch: 4
      learning_rate_schedule: linear
      beta_schedule: constant
      epsilon_schedule: linear
    network_settings:
      normalize: false
      hidden_units: 256
      num_layers: 2
    reward_signals:
      extrinsic:
        gamma: 0.8
        strength: 1
      # gail:
      #   gamma: 0.9
      #   strength: 0.6
      #   use_actions: true
      #   demo_path: Demos/BulletFinalArena.demo
      curiosity:
        gamma: 0.9
        strength: 0.1
        learning_rate: 0.0003
        encoding_size: 64
    max_steps: 2000000
    time_horizon: 64
    summary_freq: 10000
    # self_play:
    #   window: 5
    #   play_against_latest_model_ratio: 0.5
    #   save_steps: 20000
    #   swap_steps: 10000
    #   team_change: 100000